version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: creditcard_approval_service
    volumes:
      - ./creditcard_approval_service:/creditcard_approval_service/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: creditcard_approval_db
    volumes:
      - ./postgres_data:/postgresql/data/
    environment: 
      - POSTGRES_DB=alemenodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
